apiVersion: v1
kind: ConfigMap
metadata:
  name: smarterzip-config
  namespace: smarterzip
data:
  NODE_ENV: 'production'
  DATABASE_PATH: '/app/db/SmarterZip.sqlite3'
  DATABASE_LOGGING_ENABLED: 'false'
  API_URL: 'http://web:3000/api'
