apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: smarterzip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: smarterzip-scheduler:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: smarterzip-config
            - secretRef:
                name: smarterzip-secrets
          volumeMounts:
            - name: db-volume
              mountPath: /app/db
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '250m'
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: smarterzip-db-pvc
