apiVersion: v1
kind: PersistentVolume
metadata:
  name: smarterzip-db-pv
  namespace: smarterzip
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  hostPath:
    path: /mnt/data/databases/sqlite
