apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smarterzip-db-pvc
  namespace: smarterzip
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: ''
