name: Build

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint && npm run prettier

      - name: Create dummy config files
        run: |
          cp src/app/api/config/devices.json.example src/app/api/config/devices.json
          cp src/app/api/config/ignoredDevices.json.example src/app/api/config/ignoredDevices.json
          cp src/app/api/config/rooms.json.example src/app/api/config/rooms.json

      - name: Build
        run: npm run build && npm run scheduler:build

      - name: Audit
        run: npm audit

      - name: Run tests
        run: npm run test

      - name: Lint Dockerfiles
        run: npm run lint:dockerfiles

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker web image
        run: docker build -t smarterzip-web -f src/app/Dockerfile .

      - name: Build Docker scheduler image
        run: docker build -t smarterzip-scheduler -f src/scheduler/Dockerfile .
