name: Build

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint && npm run prettier

      - name: Build
        run: npm run build && npm run scheduler:build

      - name: Audit
        run: npm run audit

      - name: Run tests
        run: npm run test

      - name: Lint Dockerfiles
        run: npm run lint:dockerfiles
