name: Build

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint && npm run prettier

      - name: Create dummy config files
        run: |
          cp src/app/api/config/devices.json.example src/app/api/config/devices.json
          cp src/app/api/config/ignoredDevices.json.example src/app/api/config/ignoredDevices.json
          cp src/app/api/config/rooms.json.example src/app/api/config/rooms.json

      - name: Build
        run: npm run build && npm run scheduler:build

      - name: Audit
        run: npm audit

      - name: Run tests
        run: npm run test

      - name: Lint Dockerfiles
        run: npm run lint:dockerfiles

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push web Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/app/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/smarterzip-web:latest
          build-args: NEXT_PUBLIC_API_URL=http://localhost:6613/api

      - name: Build and push scheduler Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/scheduler/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/smarterzip-scheduler:latest

      # - name: Build Docker web image
      #   run: docker build --build-arg NEXT_PUBLIC_API_URL=http://localhost:6613/api -t ghcr.io/${{ github.repository_owner }}/smarterzip-web:latest -f src/app/Dockerfile .

      # - name: Build Docker scheduler image
      #   run: docker build -t ghcr.io/${{ github.repository_owner }}/smarterzip-scheduler:latest -f src/scheduler/Dockerfile .

      # - name: Log in to GitHub Container Registry
      #   run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Push web image
      #   run: docker push ghcr.io/${{ github.repository_owner }}/smarterzip-web:latest

      # - name: Push scheduler image
      #   run: docker push ghcr.io/${{ github.repository_owner }}/smarterzip-scheduler:latest
